# Generated by Django 3.2.5 on 2021-07-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_auto_20210721_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='addres',
            new_name='address',
        ),
    ]
